fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    configs:
        my_config:
            toolbar: 
                - ['Styles','Format','Font','FontSize']
                - '/'
                - ['Bold','Italic','Underline','StrikeThrough','-','Undo','Redo','-','Cut','Copy','Paste','Find','Replace','-','Outdent','Indent','-','Print']
                - '/'
                - ['NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock']
                - ['Image','Table','-','Link','Smiley','TextColor','BGColor','Source']
