liip_imagine :

    resolvers :
        default :
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "image/cache"

    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public"

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction


    filter_sets :

        cache : ~

        field :
            quality : 75
            filters :
                thumbnail :
                    size : [500, 281]
                    mode : inset

        profile_pic:
            quality: 75
            filters : 
                thumbnail : 
                    size : [400, 567]
                    mode : outbound

        position:
            quality: 75
            filters:
                thumbnail:
                    size: [50, 65]
                    mode: outbound

        gallery:
            quality: 100
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbond

        team-landing:
            quality: 50
            filters:
                thumbnail:
                    size: [500,500]
                    mode: outbond

        navbar:
            quality: 100
            filters:
                thumbnail:
                    size: [200,200]
                    mode: inset

        userNavbar:
            quality: 100
            filters:
                thumbnail:
                    size: [40, 40]
                    mode: outbond
        
        news:
            quality: 100
            filters:
                thumbnail:
                    size: [240, 90]
                    mode: inset
        
        favicon:
            quality: 50
            filters:
                thumbnail:
                    size: [64, 64]
                    mode: inset
        
        carousel:
            quality: 100
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbond


