vich_uploader:
    db_driver: orm

    mappings:
        picture:
            uri_prefix: /picture/upload
            upload_destination: '%kernel.project_dir%/public/picture/upload'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
