vich_uploader:
    db_driver: orm
 
    mappings:
        picture:
            uri_prefix: '%path_image%' 
            upload_destination: '%kernel.project_dir%/public/%path_image%' 
            namer: Vich\UploaderBundle\Naming\UniqidNamer 
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
