easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin/{_locale}
    type: annotation
    defaults:
        _locale: en_US
    requirements:
        _locale: '%supported_locales%'