user:
    resource: "Route/UserRouting.yaml" 
    prefix: /{_locale}/user/
    requirements:
        _locale: '%supported_locales%'

Security:
    resource: "Route/SecurityRouting.yaml"
    prefix: /{_locale}/
    requirements:
        _locale: '%supported_locales%'

blog:
    resource: "Route/BlogRouting.yaml"
    prefix: /{_locale}/blog/
    requirements:
        _locale: '%supported_locales%'

comment:
    resource: "Route/CommentRouting.yaml"
    prefix: /{_locale}/comment/
    requirements:
        _locale: '%supported_locales%'

home:
    resource: "Route/DefaultRouting.yaml"
    prefix: /{_locale}/
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '%supported_locales%'

admin:
    resource: "Route/AdminRouting.yaml"
    prefix: /{_locale}/admin/
    requirements:
        _locale: '%supported_locales%'

event:
    resource: "Route/EventRouting.yaml"
    prefix: /{_locale}/event/
    requirements:
        _locale: '%supported_locales%'

chat:
    resource: "Route/ChatRouting.yaml"
    prefix: /{_locale}/chat/
    requirements:
        _locale: '%supported_locales%'

team:
    resource: "Route/TeamRouting.yaml"
    prefix: /{_locale}/team/
    requirements:
        _locale: '%supported_locales%'

aside:
    resource: "Route/AsideRouting.yaml"
    prefix: /{_locale}/aside/
    requirements:
        _locale: '%supported_locales%'

gallery:
    resource: "Route/GalleryRouting.yaml"
    prefix: /{_locale}/gallery/
    requirements:
        _locale: '%supported_locales%'