user:
    resource: "../src/Route/UserRouting.yaml" 
    prefix: /

Security:
    resource: "../src/Route/SecurityRouting.yaml"
    prefix: /

blog:
    resource: "../src/Route/BlogRouting.yaml"
    prefix: /