user:
    resource: "Route/UserRouting.yaml" 
    prefix: /

Security:
    resource: "Route/SecurityRouting.yaml"
    prefix: /

blog:
    resource: "Route/BlogRouting.yaml"
    prefix: /blog/

home:
    resource: "Route/DefaultRouting.yaml"
    prefix: /

admin:
    resource: "Route/AdminRouting.yaml"
    prefix: /admin/

event:
    resource: "Route/EventRouting.yaml"
    prefix: /event/

chat:
    resource: "Route/ChatRouting.yaml"
    prefix: /chat/

team:
    resource: "Route/TeamRouting.yaml"
    prefix: /team/

image:
    resource: "Route/ImageRouting.yaml"
    prefix: /image/

aside:
    resource: "Route/AsideRouting.yaml"
    prefix: /aside/