# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
parameters:
    locale: 'en_US'
    supported_locales: en_US|es_ES|fr_FR
    twig_locales: [en_US, es_ES, fr_FR]

    path_image: image/upload
    
    algolia_place_app_id: '%env(ALGOLIA_PLACE_APP_ID)%'
    algolia_place_api_id: '%env(ALGOLIA_PLACE_API_ID)%'
    
    club_name: '%env(CLUB_NAME)%'
    
    chat_update_interval: 10000


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $defaultLocale: locale

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    image.manager:
        class: App\Utils\ImageManager
        

    App\EventListener\UpdateTime:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\CreateParticipations:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments: [ "@doctrine.orm.entity_manager" ]

    App\EventListener\ImageListener:
        arguments:
            $path_image: "%path_image%"
        tags:
            - {name: doctrine.event_listener, event: postUpdate}
            - {name: doctrine.event_listener, event: preRemove}
            - {name: doctrine.event_listener, event: postPersist}
            - {name: kernel.event_listener, event: vich_uploader.pre_inject }

    App\EventListener\FieldListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\EventListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    
    App\EventListener\NewsListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\CommentListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    App\EventListener\ChatListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\PersonnalStatListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    
    App\EventListener\EventTagListener:
        tags:
            - {name: doctrine.event_listener, event: preRemove}
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\PlayerTagListener:
        tags:
            - {name: doctrine.event_listener, event: preRemove}

    App\EventListener\FeatureTagListener:
        tags:
            - {name: doctrine.event_listener, event: preRemove}

    App\EventListener\StatTagListener:
        tags:
            - {name: doctrine.event_listener, event: preRemove}

    App\EventListener\LocationListener:
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    App\EventListener\FieldTemplateListener:
        tags:
            - { name: doctrine.event_listener, event: preRemove, priority: 500 }
            - { name: doctrine.event_listener, event: preUpdate, priority: 500 }

    App\Service\EmailService:
        arguments: 
            - '@swiftmailer.mailer.default'
            - '%env(WEBMASTER_MAIL)%'
    
    App\Twig\CountryExtention:
        tags:
            - { name: twig.extention }

    App\EventListener\GalleryListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
